In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
from __future__ import print_function
from builtins import range
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(142)

In [2]:
# load data by using pandas command [pd.read_csv]
data= pd.read_csv('SPAM text message.csv')
data

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
data['Category'].replace(['spam','ham'],[0,1],inplace=True)

In [4]:
coun_vect = CountVectorizer(stop_words= 'english',max_df=0.65)
count_matrix = coun_vect.fit_transform(data.Message)
count_array = count_matrix.toarray()
df = pd.DataFrame(data=count_array,columns = coun_vect.get_feature_names())
df

C:\Users\emana\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,0125698789,02,...,zhong,zindgi,zoe,zogtorius,zoom,zouk,zyada,èn,ú1,〨ud
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5568,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5569,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5570,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5571,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
# define df as X
X=df
X

,00,000,000pes,008704050406,0089,0121,01223585236,01223585334,0125698789,02,...,zhong,zindgi,zoe,zogtorius,zoom,zouk,zyada,èn,ú1,〨ud
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5568,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5569,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5570,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5571,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
# define target column "Category" as y 
y=data['Category']
y

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: int64

In [7]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size = 0.3,random_state=42)

In [8]:
train_x = torch.Tensor(x_train.values)
test_x = torch.Tensor(x_test.values)

In [9]:
#hyperparameters
hl1 = 500
hl2 = 80
#hl3 = 10
lr = 0.01
num_epoch = 800

In [13]:
#build model
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(8440, hl1)
        self.fc3 = nn.Linear(hl1,hl2)
      #  self.fc4 = nn.Linear(hl2,hl2)
        #self.fc5 = nn.Linear(hl2,hl2)
        self.fc2 = nn.Linear(hl2, 2)

    def forward(self, x):
        x = F.tanh(self.fc1(x))
        x = F.tanh(self.fc3(x))
       # x = F.relu(self.fc4(x))
        #x = F.relu(self.fc5(x))
       
        x = F.sigmoid(self.fc2(x))
        return x
        
net = Net()

In [14]:
#choose optimizer and loss function
criterion = nn.CrossEntropyLoss()
#optimizer = torch.optim.SGD(net.parameters(), lr=lr)
#optimizer = torch.optim.Adagrad(net.parameters(), lr=lr)
optimizer = torch.optim.Adam(net.parameters(), lr=lr)
#optimizer = torch.optim.SGD(net.parameters(), lr=lr, momentum=0.9)
#optimizer = torch.optim.RMSprop(net.parameters(), lr=lr)

In [15]:
#train
import time

for epoch in range(num_epoch):
    X = torch.Tensor(train_x).float()
    Y = torch.Tensor(y_train).long()

    #feedforward - backprop
    optimizer.zero_grad()
    out = net(X)
    loss = criterion(out, Y)
    loss.backward()
    optimizer.step()
    acc = 100 * torch.sum(Y==torch.max(out.data, 1)[1]).double() / len(Y)
    if (epoch % 50 == 1):
	    print ('Epoch [%d/%d] Loss: %.4f   Acc: %.4f' 
                   %(epoch+1, num_epoch, loss.item(), acc.item()))

C:\Users\emana\anaconda3\lib\site-packages\torch\nn\functional.py:1795: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
C:\Users\emana\anaconda3\lib\site-packages\torch\nn\functional.py:1806: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")

Epoch [2/800] Loss: 0.6033   Acc: 97.8462
Epoch [52/800] Loss: 0.3140   Acc: 99.9231
Epoch [102/800] Loss: 0.3140   Acc: 99.9231
Epoch [152/800] Loss: 0.3140   Acc: 99.9231
Epoch [202/800] Loss: 0.3140   Acc: 99.9231
Epoch [252/800] Loss: 0.3140   Acc: 99.9231
Epoch [302/800] Loss: 0.3140   Acc: 99.9231
Epoch [352/800] Loss: 0.3140   Acc: 99.9231
Epoch [402/800] Loss: 0.3140   Acc: 99.9231
Epoch [452/800] Loss: 0.3140   Acc: 99.9231
Epoch [502/800] Loss: 0.3140   Acc: 99.9231
Epoch [552/800] Loss: 0.3140   Acc: 99.9231
Epoch [602/800] Loss: 0.3140   Acc: 99.9231
Epoch [652/800] Loss: 0.3140   Acc: 99.9231
Epoch [702/800] Loss: 0.3140   Acc: 99.9231
Epoch [752/800] Loss: 0.3140   Acc: 99.9231

In [16]:
"""
SECTION 3 : Testing model
"""
test_y = torch.Tensor(y_test.values)


#get prediction
X = torch.Tensor(test_x).float()
Y = torch.Tensor(test_y)
out = net(X)
_, predicted = torch.max(out.data, 1)

#get accuration
print('Accuracy of testing %.4f %%' % (100 * torch.sum(Y==predicted).double() / len(Y)))

Accuracy of testing 98.9833 %